---
- hosts: all
  become: true
  roles:
    - baseline

- hosts: edge
  become: true
  roles:
    - edge

- hosts: vault
  become: true
  roles:
    - vault

- hosts: k3s
  become: true
  roles:
    - k3s

- hosts: pg
  become: true
  roles:
    - pg

- hosts: minio
  become: true
  roles:
    - minio
